const MetrolinkStations = {
    AllStations: [
        'Shiloh Scott',
        'College',
        'Belleville',
        'Swansea',
        'Memorial Hospital',
        'Fairview Heights',
        'Washington Park',
        'Jackie Joyner-Kersee',
        'Emerson Park',
        '5th & Missouri',
        'East Riverfront',
        'Lacledes Landing',
        'Convention Center',
        '8th & Pine',
        'Stadium',
        'Civic Center',
        'Union Station',
        'Grand',
        'Cortex',
        'Central West End',
        'Forest Park',
        'Delmar',
        'Wellston',
        'Rock Road',
        'UMSL South',
        'UMSL North',
        'North Hanley',
        'Lambert Airport Terminal 2',
        'Lambert Airport Terminal 1',
        'Skinker',
        'University City-Big Bend',
        'Forsyth',
        'Clayton',
        'Richmond Heights',
        'Brentwood',
        'Maplewood',
        'Sunnen',
        'Shrewsbury'
    ],

    RedStations: [
        'Shiloh Scott',
        'College',
        'Belleville',
        'Swansea',
        'Memorial Hospital',
        'Delmar',
        'Wellston',
        'Rock Road',
        'UMSL South',
        'UMSL North',
        'North Hanley',
        'Lambert Airport Terminal 2',
        'Lambert Airport Terminal 1',
    ],

    BlueStations: [
        'Skinker',
        'University City-Big Bend',
        'Forsyth',
        'Clayton',
        'Richmond Heights',
        'Brentwood',
        'Maplewood',
        'Sunnen',
        'Shrewsbury'
    ]
}

export default MetrolinkStations;